const actionTypes = {
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_ERROR: 'AURH_LOGIN_ERROR',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
	LOAD_MY_PROFILE: 'LOAD_MY_PROFILE',
	LOAD_PLACE_DATA: 'LOAD_PLACE_DATA',
	LOAD_PLACE_ID: 'LOAD_PLACE_ID'
};

export default actionTypes;
